# -*- coding: utf-8 -*-
"""examen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ejHJyJsQzbujXU1mSk-_eyvqUehOReHo
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('AmericaTemperaturesByCity.csv', encoding='latin-1')
df

df.info()

sns.heatmap(df.isnull())

df.isnull().sum()

df.corr
df

dfmex = df[df['Country'] == 'Mexico']
dfmex

dfmex['City'].unique()

df.drop(columns=["AverageTemperatureUncertainty"],inplace = True)

df.info()

df.isnull().sum()



df.isnull().sum()

# Convert 'dt' column to datetime type if it's not already
df['dt'] = pd.to_datetime(df['dt'])

# Extract Year, Month, and Day into new columns
df['Year'] = df['dt'].dt.year
df['Month'] = df['dt'].dt.month
df['Day'] = df['dt'].dt.day

# Display the first few rows to show the new columns
display(df.head())

# solo quiero que en 'Country' aparezca mexico
df = df[df['Country'] == 'Mexico']
df

df.replace({'Country':{ 'Acapulco':0, 'Acuña':1, 'Aguascalientes':2}},inplace=True)

X = pd.DataFrame(dfmex, columns=['Day', 'Month', 'Year'])
y = dfmex['AverageTemperature']

X

y

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1613808)
y_train

from sklearn.linear_model import LinearRegression
LR = LinearRegression()

LR.fit(X_train,y_train)

LR.score(X_train, y_train)

pred = LR.predict(X_test)
pred

comparacion = X_test.copy()
comparacion = comparacion.join(y_test)
comparacion['Predicción'] = pred
comparacion

b1 = LR.coef_
print("Coeficiente b1: \n", b1)

b0 = LR.intercept_
print("Intersección: \n", b0)

dia = 25
mes = 12
año = 1990

temperatura_predicha = b0 + b1[0]*dia + b1[1]*mes + b1[2]*año

print("La temperatura estimada es:", temperatura_predicha)

from sklearn.metrics import r2_score

r2 = r2_score(y_test, pred)
print("R2 score:", r2)